### ISSUE TITLE
1/21/16-1/28/16

### ISSUE THREAD

**Issue by ClaudeTheCazur** [CodeForChicago/SuperClass-frontend#1]
Issues to solve: There are merge conflicts. Everyone take a look and report on them. 
Goals for this week: Resolve conflicts. Push more to dev branch. Prettify pages(4 real man). Get more lessons. Set up API.

**Comment by BenSandeen** [comment]
**Contact Github help team for support in isolating the issue**

**Comment by ClaudeTheCazur** [comment]
Issue is now obsolete. Closing
